### ISSUE TITLE
InputBinder GUI seemingly stops working randomly

### ISSUE THREAD

**Issue by MyCatMoss** [Codenade/ksp2-inputbinder#14]
For many of the bindings in the GUI, there are two submenus within each action. For instance, clicking "Expand" next to "WheelSteer" expands into two submenus that say:

COMPOSITE
&nbsp; 1DAxis
&ensp;  &nbsp; positive
&ensp;  &nbsp;  &ensp;  &nbsp; - Keyboard/d
&ensp;  &nbsp; negative
&ensp;  &nbsp;  &ensp;  &nbsp; - Keyboard/a
COMPOSITE
&ensp; 1DAxis
&ensp;  &nbsp; positive
 &ensp;  &nbsp;  &ensp;  &nbsp; -
&ensp;  &nbsp; negative
 &ensp;  &nbsp;  &ensp;  &nbsp; -

What is the purpose of the second identical submenu? I initially figured it was to allow two different input bindings tied to one action (i.e. so you can switch between using a keyboard and a controller.) The PROBLEM is, anytime I try to manipulate the second submenu (that always has no bindings by default) the InputBinder GUI stops responding to input from any of my devices when trying to "Change" the binding - including keyboard. 

To be clear, this is what happens once the problem starts: I click "Change", the button changes appearance to show it has been clicked, so I activate whatever I'd like that particular input to be, but the results field doesn't change from "None" to reflect it has recognized the input signal I just submitted.

If it matters, I am trying to set up controls for a HOTAS (VKB Gladiator NXT).

**Comment by Codenade** [comment]
Hey @MyCatMoss, thanks for submitting this issue!


> What is the purpose of the second identical submenu?

The reason why you see a second submenu is because KSP2 has two composite bindings (displayed in Inputbinder as submenus) attached to every action, they are loaded from the game.  
The first one seems to be intended by the devs to hold keyboard bindings and the second one seems to be intended to hold gamepad bindings. However I didn't intend to limit the types of assignable controls with Inputbinder. 
You should also be able to use them like you said: To allow two different devices (e.g. keyboard and controller) to be used.

## The problem
By default Unity's Inputsystem's [RebindingOperation](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.5/api/UnityEngine.InputSystem.InputActionRebindingExtensions.RebindingOperation.html) only accepts the same device type as the original (e.g. for the first submenu this would in the most cases be a Keyboard and for the second one mostly a Gamepad). This means that when you were trying to assign something different, the mod would wait for you to assign the matching device. Due to missing GUI hints it would now seem to be stuck or crashed, however you can abort the rebinding process by pressing **ESC**.

## The fix
**I was able to reproduce the problem and have implemented a fix, available from:**
https://github.com/Codenade/ksp2-inputbinder/releases/tag/experimental
The mod should now accept Input from any compatible device.
**_It would be very helpful if you could see if your issue still persisists before I release a new version._** 🙏
Before I publish a full release however, I would like to make it more clear to the user as to when the GUI is in Rebinding mode and therefore unresponsive and also highlight the fact that you can cancel the operation by pressing ESC.

## Another question
Does your HOTAS generally work with Inputbinder? Just curious as I wanna see what general compatibility with other hardware looks like. 
So far I had problems with one device. Specifically the Thrustmaster T-Flight Rudder Pedals as they are not supported out of the box by the Unity Inputsystem.

**Comment by Codenade** [comment]
Since everything seems to be working now on my end I am gonna get ready to publish a new release of this mod. The bleeding edge build can still be found at https://github.com/Codenade/ksp2-inputbinder/releases/tag/experimental
