### ISSUE TITLE
Cannot Map X52 Z Rotation to Yaw

### ISSUE THREAD

**Issue by roldershaw** [Codenade/ksp2-inputbinder#17]
Hi,

Just testing this out for the first time. I cannot map the Rotation Axis's to any value. Only the XYZ (Z in this case being the throttle will map)

The slider also won't map.

The main issue is I cannot twist the stick which is the z rotation to the yaw but being able to use other rotation axis would be good too.

Also it would be really good if I could control camera position using a POV hat.

Thanks.

**Comment by Codenade** [comment]
Hello, 

I have mostly been using my Dualshock 4 gamepad and some old joystick I had laying around for testing and the only problem I encountered so far was that the POV hat would only register an input in the up direction regardless of which way I actually moved it.
These controllers I used for testing did not have a rotation axis so thats likely why I havent run into this issue while testing.

I'm currently looking for a solution for the problem after having reproduced it with a Raspberry Pi Pico imitating a custom HID.

When I have something ready I'll comment on this issue.

**Comment by Codenade** [comment]
Hey @roldershaw, could you please try assigning your Z Rotation to the "Throttle Axis"?

The problem seems to be that for most devices, Unity's Inputsystem treats the x and y axes differently than z, rx, ry and rz. The latter ones are only assignable to an actual axis action (e.g. Throttle Axis). The x and y axes are usually combined into a stick control which contains button controls named up, down, left, right. This is what makes them assignable to the composite bindings.

I am looking at different options to make axes assignable too. (Maybe adding an extra dialog where you can choose wherther you want to assign a control as an axis or a button. Or adding an additional binding specifically for axis controls.) 

As for the D-Pad: I have tried my old joystick and the inputsystem seems generally confused with the D-Pad. It is working without issues on the DS4 controller. I have yet to test using the Raspberry Pi Pico.

**Comment by roldershaw** [comment]
I'll give this a test tomorrow :)

**Comment by roldershaw** [comment]
Ah yes you are right, RZ can map to the throttle axis and works as expected.

In KSP1 AFBW can map the RZ, but it does just show everything as an Axis, maybe it remaps them somehow?

![image](https://github.com/Codenade/ksp2-inputbinder/assets/879375/58ee417a-c112-424a-ac46-6b22f31e264f)

**Comment by Codenade** [comment]
I will implement adding another binding to which you should be able to bind x, y, z, rx, ry and rz. I will update the experimental release on github when I am done so you can test it.

>In KSP1 AFBW can map the RZ, but it does just show everything as an Axis, maybe it remaps them somehow?

AFBW more or less directly uses the lower level APIs (SDL, DirectInput, XInput). I chose not to use them because KSP 2 already comes with Unity's [Inputsystem](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.5/manual/index.html) bundled and I figured it would be quicker to implement something. Also the games uses the [Inputsystem](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.5/manual/index.html) for its controls so it is easy to modify them.

**Comment by Codenade** [comment]
I have the implementation ready: https://github.com/Codenade/ksp2-inputbinder/releases/tag/experimental

There is now an extra binding for axes on actions where it makes sense:

![Demo](https://github.com/Codenade/ksp2-inputbinder/assets/19842648/35aa9333-fd1e-4219-9c22-05ec0f576f2c)

If you have any suggestions let me know!

**Comment by Aviage-01** [comment]
I was having the same issue as Rolder. Is it possible to install the experimental branch via CKAN?

**Comment by Aviage-01** [comment]
Thanks very much! I'll give both of those a go!

**Comment by Codenade** [comment]
I have updated the experimental version to reflect the latest changes in [17-cannot-map-x52-z-rotation-to-yaw](https://github.com/Codenade/ksp2-inputbinder/tree/17-cannot-map-x52-z-rotation-to-yaw). This should also close #21. 
Please check if the issues still persist!
