### ISSUE TITLE
Cannot rebind kerbal EVA controls

### ISSUE THREAD

**Issue by RadioFreeKerbin** [Codenade/ksp2-inputbinder#35]
### Description

While it's great that rover controls can be rebound, it appears that kerbal EVA controls revert to WASD and there is no option to change the bindings to anything else, unlike in the stock settings, which becomes unavailable. 

### Steps to reproduce

Install mod, set bindings using in game menu, launch mission and eva kerbal, realized there is no option to bind these controls. 

### Expected behaviour

That EVA controls would also have key bindings. Would be great to have an option for analog axes for Eva packs, not sure if game supports this. Other in game hotkeys, such as F2 should still work or have a rebind option

### Workarounds

Unknown

### Additional information

This is more a feature request than a bug report.

**Comment by RadioFreeKerbin** [comment]
To add: this also seems to affect other default game bindings, for instance, with this mod installed, I can no longer press F2 to hide the UI

**Comment by Codenade** [comment]
Hello @RadioFreeKerbin, you could put [this (Click to download)](https://github.com/Codenade/ksp2-inputbinder/files/13967039/game_actions_to_add.txt) file into Kerbal Space Program 2/BepInEx/config/inputbinder/

When I have more time I will probably add them to the in-game menu.

The issue with F2 not working should be fixed by #38 I havent made a new release yet but you can [download the build artifacts](https://github.com/Codenade/ksp2-inputbinder/actions/runs/7559386605/artifacts/1175903462) from github actions and install it manually.

**Comment by RadioFreeKerbin** [comment]
Thank you for the reply, I will try that thanks.

And thanks for your amazing work on this mod! It is very much appreciated by me and other members of the community!

**Comment by Codenade** [comment]
Added EVA Actions in b7fa9f0d0714595a3c0d42f4aa5203c3a751e157

**Comment by Codenade** [comment]
@RadioFreeKerbin once you install version 0.5.3 you may have ro remove game_actions_to_add.txt again (or remove the EVA actions from the file) in order for the mod to work.

**Comment by RadioFreeKerbin** [comment]
Not sure if you will get this message since the issue is closed, but I noticed I don't have control of my preferred keys (numpad) in the VAB, and there are no in-game menu options to do this. I assume I can do this by editing the game_actions_to_add.txt file, but I'll need to find the syntax. Also, this might be something to add to the menu in a future release, so that users will be able to customize those functions.
